artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/anuj6263/Wine_Quality_Assessment/blob/main/Inequality%20in%20Education.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion